hostname: rock

user: vagrant
group: vagrant

php_error_reporting: E_ALL
php_display_errors: On
php_upload_max_filesize: 20M
php_post_max_size: 25M

vhosts:
  [
    { name: 'rock.sanitize', rootFolder: '/var/www'}
  ]
